ci(docker): add check on size

diff --git a/.github/workflows/release-nextjs-app-docker.yml b/.github/workflows/release-nextjs-app-docker.yml
--- a/.github/workflows/release-nextjs-app-docker.yml
+++ b/.github/workflows/release-nextjs-app-docker.yml
@@ -90,6 +90,12 @@ jobs:
         run: docker save ${{ env.IMAGE }}:${{ steps.meta.outputs.version }} -o ./docker-image.tar
 
       - name: 📐 Compress saved image and show size
+        env:
+          MAX_SIZE: 80
         run: |
           zstd -5 -i ./docker-image.tar -o ./docker-image.tar.zst          
           ls -lah | grep docker-image.tar
+          if [ $(ls -s --block-size=1048576 ./docker-image.tar.zst | cut -d' ' -f1)  -gt ${{ env.MAX_SIZE }} ]; then 
+             echo 'Error: docker image too big'; 
+             exit 1; 
+          else echo "Size ok"; fi
